# Generated by Django 3.1.3 on 2021-01-05 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='Desc',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='duty_schedule',
            name='Month',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='duty_schedule',
            name='Time_in',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='duty_schedule',
            name='Time_out',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Dept',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Designation',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Emp_id',
            field=models.CharField(default='None', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='PhoneNo',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='From',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Reason',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='To',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salary_mgmt',
            name='AC_No',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='salary_mgmt',
            name='Bank_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='salary_mgmt',
            name='IFSC',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
