# Generated by Django 3.1.3 on 2021-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20210105_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('PhoneNo', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee_details',
            name='name',
            field=models.CharField(default='Enter name', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='PhoneNo',
            field=models.CharField(default='Enter phone number', max_length=100),
        ),
    ]
