# Generated by Django 3.1.3 on 2021-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20210106_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_mgmt',
            name='Ded_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary_mgmt',
            name='Desc',
            field=models.CharField(default='Deduction reason', max_length=200),
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
